### ISSUE TITLE
Release a new version?

### ISSUE THREAD

**Issue by EFanZh** [est31/warnalyzer#7]
The released version 0.1.0 does not compile now:

```
error[E0432]: unresolved imports `syn::visit`, `syn::visit`
  --> /home/efanzh/.cargo/registry/src/github.com-1ecc6299db9ec823/warnalyzer-0.1.0/src/mute.rs:88:11
   |
88 |     use syn::visit::{visit_item, self};
   |              ^^^^^               ^^^^ no `visit` in the root
   |              |
   |              could not find `visit` in `syn`

error[E0433]: failed to resolve: could not find `visit` in `syn`
   --> /home/efanzh/.cargo/registry/src/github.com-1ecc6299db9ec823/warnalyzer-0.1.0/src/mute.rs:105:22
    |
105 |     impl<'ast, 'a> syn::visit::Visit<'ast> for Visitor<'a> {
    |                         ^^^^^ could not find `visit` in `syn`

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0432, E0433.
For more information about an error, try `rustc --explain E0432`.
error: failed to compile `warnalyzer v0.1.0`, intermediate artifacts can be found at `/tmp/cargo-installCYhgjx`

Caused by:
  could not compile `warnalyzer`

To learn more, run the command again with --verbose.
```

**Comment by est31** [comment]
Huh that's a weird bug. Apparently it works with syn 0.15.34 but is broken on syn 0.15.44. This is a semver breaking change of the syn crate but I don't want to bother the syn author with it. You can probably work around with `cargo install --locked` (or `cargo install --git`). I mainly released it on crates.io to reserve the name, but I'll do another release.

**Comment by est31** [comment]
[v0.2.0](https://github.com/est31/warnalyzer/releases/tag/v0.2.0) is out!
